services:
  enzyme-ml:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enzyme-ml
    restart: unless-stopped
    volumes:
      - ./results:/app/results
    ports:
      - "8888:8888"
    command: python -m jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''

  enzyme-jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: enzyme-jupyter
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./notebooks:/app/notebooks
      - ./results:/app/results
    ports:
      - "8889:8888"
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' --LabApp.token='' --LabApp.password=''

  enzyme-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: enzyme-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./results:/app/results
    depends_on:
      - enzyme-ml
    command: gunicorn --bind 0.0.0.0:5000 src.api.app:app 